# Generated by Django 4.2 on 2023-04-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdetails',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
